Models/Cliente.cs
namespace AulaDeASPNet.Models
{
    public class Cliente
    {
        public int Id { get; set; }
        public string Nome { get; set; } = string.Empty;
        public string RG { get; set; }
        public string CPF { get; set; }
        public string Usuario { get; set; }
        public string Senha { get; set; }
        public string UF { get; set; }
        public string Cidade { get; set; }
        public string Bairro { get; set; }
        public string Rua { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public string CEP {  get; set; }
        public string Telefone { get; set; }
        public string Email { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace AulaDeASPNet.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Produto.cs
namespace AulaDeASPNet.Models
{
    public class Produto
    {
        public int Id { get; set; }
        public string Descricao { get; set; } = string.Empty;
        public string Marca { get; set; } = string.Empty;
        public string Categoria { get; set; } = string.Empty;
        public decimal Preco { get; set; }
        public int Qtde { get; set; }
        public decimal Peso { get; set; }
        public decimal Largura { get; set; }
        public decimal Altura { get; set; }
    }
}

Controllers/ClienteController.cs
using AulaDeASPNet.Data;
using AulaDeASPNet.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AulaDeASPNet.Controllers
{
    public class ClienteController : Controller
    {
        private readonly AulaContext _context;

        public ClienteController(AulaContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> BuscarCliente()
        {
            return View(await _context.Clientes.ToListAsync());
        }
        public async Task<IActionResult> DetalhesCliente(int id)
        {
            return View(await _context.Clientes.FindAsync(id));
        }
        public async Task<IActionResult> AlterarCliente(int id)
        {
            return View(await _context.Clientes.FindAsync(id));
        }

        public async Task<IActionResult> CadastroCliente(int? id)
        {
            if (id == null)
            {
                return View();
            }
            else
            {
                return View(await _context.Clientes.FindAsync(id));
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CadastroCliente(
            [Bind("Nome, CPF, RG,Telefone, Email, Usuario, Senha," +
            "CEP,UF,Cidade,Bairro,Rua,Numero,Complemento")]
            Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                if (cliente.Id != 0)
                {
                    _context.Update(cliente);
                    await _context.SaveChangesAsync();

                }
                else
                {
                    _context.Add(cliente);
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction("BuscarClientes");
            }
            return View(cliente);
        }
    }
}

Controllers/HomeController.cs
using AulaDeASPNet.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AulaDeASPNet.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/NossoAppController.cs
using Microsoft.AspNetCore.Mvc;

namespace AulaDeASPNet.Controllers
{
    public class NossoAppController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ProdutoController.cs
using AulaDeASPNet.Data;
using AulaDeASPNet.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AulaDeASPNet.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly AulaContext _context;

        public ProdutoController(AulaContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> BuscarProduto()
        {
            return View(await _context.Clientes.ToListAsync());
        }
        public async Task<IActionResult> DetalhesProduto(int id)
        {
            return View(await _context.Clientes.FindAsync());
        }
        public async Task<IActionResult> AlterarProduto(int id)
        {
            return View(await _context.Clientes.FindAsync(id));
        }

        public async Task<IActionResult> CadastroProdutoAsync(int? id)
        {
            {
                if (id == null)
                {
                    return View();
                }
                else
                {
                    return View(await _context.Produtos.FindAsync(id));
                }
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CadastroProduto(
           [Bind("Descricao,Marca,Categoria,Preco,Qtde,Peso,Largura,Altura")]
            Produto produto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(produto);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "NossoApp");
            }
            return View(produto);
        }
    }
}

Views/Cliente/AlterarCliente.cshtml
@model AulaDeASPNet.Models.Cliente

@{
    ViewData["Title"] = "AlterarCliente";
    Layout = "~/Views/Shared/_NossoLayout.cshtml";
}

<h1>AlterarCliente</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AlterarCliente">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RG" class="control-label"></label>
                <input asp-for="RG" class="form-control" />
                <span asp-validation-for="RG" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CPF" class="control-label"></label>
                <input asp-for="CPF" class="form-control" />
                <span asp-validation-for="CPF" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Usuario" class="control-label"></label>
                <input asp-for="Usuario" class="form-control" />
                <span asp-validation-for="Usuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Senha" class="control-label"></label>
                <input asp-for="Senha" class="form-control" />
                <span asp-validation-for="Senha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UF" class="control-label"></label>
                <input asp-for="UF" class="form-control" />
                <span asp-validation-for="UF" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cidade" class="control-label"></label>
                <input asp-for="Cidade" class="form-control" />
                <span asp-validation-for="Cidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bairro" class="control-label"></label>
                <input asp-for="Bairro" class="form-control" />
                <span asp-validation-for="Bairro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rua" class="control-label"></label>
                <input asp-for="Rua" class="form-control" />
                <span asp-validation-for="Rua" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Numero" class="control-label"></label>
                <input asp-for="Numero" class="form-control" />
                <span asp-validation-for="Numero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Complemento" class="control-label"></label>
                <input asp-for="Complemento" class="form-control" />
                <span asp-validation-for="Complemento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CEP" class="control-label"></label>
                <input asp-for="CEP" class="form-control" />
                <span asp-validation-for="CEP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-primary" asp-action="BuscarCliente">Voltar para a lista</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Cliente/BuscarCliente.cshtml
@model IEnumerable<AulaDeASPNet.Models.Cliente>

@{
    ViewData["Title"] = "BuscarCliente";
    Layout = "~/Views/Shared/_NossoLayout.cshtml";
}

<h1>BuscarCliente</h1>

<p>
    <a class="btn btn-info" asp-action="Create">Criar Novo</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RG)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CPF)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Usuario)
            </th>
            @*   <th>
            @Html.DisplayNameFor(model => model.Senha)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.UF)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.Cidade)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.Bairro)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.Rua)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.Numero)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.Complemento)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.CEP)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.Telefone)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.Email)
            </th> *@
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RG)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CPF)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Usuario)
                </td>
                @*   <td>
            @Html.DisplayFor(modelItem => item.Senha)
            </td>
            <td>
            @Html.DisplayFor(modelItem => item.UF)
            </td>
            <td>
            @Html.DisplayFor(modelItem => item.Cidade)
            </td>
            <td>
            @Html.DisplayFor(modelItem => item.Bairro)
            </td>
            <td>
            @Html.DisplayFor(modelItem => item.Rua)
            </td>
            <td>
            @Html.DisplayFor(modelItem => item.Numero)
            </td>
            <td>
            @Html.DisplayFor(modelItem => item.Complemento)
            </td>
            <td>
            @Html.DisplayFor(modelItem => item.CEP)
            </td>
            <td>
            @Html.DisplayFor(modelItem => item.Telefone)
            </td>
            <td>
            @Html.DisplayFor(modelItem => item.Email)
            </td> *@
                <td>
                    <a class="btn btn-warning" asp-action="AlterarCliente" asp-route-id="@item.Id">Alterar</a> |
                    <a class="btn btn-info" asp-action="DetalhesCliente" asp-route-id="@item.Id">Detalhes</a> |
                    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Cliente/CadastroCliente.cshtml
@model AulaDeASPNet.Models.Cliente

@{
    ViewData["Title"] = "Cadastro Cliente";
}
@* Código Formulário Cadastro Cliente *@
<div class="container">
    @* LINHA TITULO *@
    <div class="row">
        <div class="col text-center">
            <h1>❉ Cadastro Cliente ❉</h1>
        </div>
    </div>
    <form method="post">
        @* LINHA NOME E CPF *@
        <div class="row">
            <div class="col">
                <label asp-for="Nome" class="col-sm2 col-form-label fw-bold"></label>
                <input asp-for="Nome" class="form-control" id="Nome" type="text" />
            </div>
            <div class="col-lg-3">
                <label asp-for="CPF" class="col-form-label fw-bold"></label>
                <input asp-for="CPF" class="form-control" id="CPF" type="text" />
            </div>
            <div class="col-lg-2">
                <label asp-for="RG" class="col-form-label fw-bold"></label>
                <input asp-for="RG" class="form-control" id="RG" type="text" />
            </div>
            <div class="col-lg-2">
                <label asp-for="Telefone" class="col-form-label fw-bold"></label>
                <input asp-for="Telefone" class="form-control" id="Telefone" type="text" />
            </div>
            <div class="col-lg-2">
                <label asp-for="Email" class="col-form-label fw-bold"></label>
                <input asp-for="Email" class="form-control" id="Email" type="text" />
            </div>
        </div>
        <div class="row">
            <div class="col">
                <label asp-for="Usuario" class="col-sm2 col-form-label fw-bold"></label>
                <input asp-for="Usuario" class="form-control" id="Usuario" type="text" />
            </div>
            <div class="col">
                <label asp-for="Senha" class="col-form-label fw-bold"></label>
                <input asp-for="Senha" class="form-control" id="Senha" type="text" />
            </div>
        </div>

        @* LINHA ENDEREÇO *@
        <div class="row">
            <div class="col-sm-2">
                <label asp-for="CEP" class="col-sm2 col-form-label fw-bold"></label>
                <input asp-for="CEP" class="form-control" id="CEP" type="text" />
            </div>
            <div class="col-sm-2">
                <label asp-for="UF" class="col-form-label fw-bold"></label>
                <input asp-for="UF" class="form-control" id="UF" type="text" />
            </div>
            <div class="col-sm-2">
                <label asp-for="Cidade" class="col-form-label fw-bold"></label>
                <input asp-for="Cidade" class="form-control" id="Cidade" type="text" />
            </div>
            <div class="col-sm-2">
                <label asp-for="Bairro" class="col-form-label fw-bold"></label>
                <input asp-for="Bairro" class="form-control" id="Bairro" type="text" />
            </div>
            <div class="col-sm-3">
                <label asp-for="Rua" class="col-form-label fw-bold"></label>
                <input asp-for="Rua" class="form-control" id="Rua" type="text" />
            </div>
            <div class="col">
                <label asp-for="Numero" class="col-form-label fw-bold"></label>
                <input asp-for="Numero" class="form-control" id="Numero" type="text" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-10">
                <label asp-for="Complemento" class=" col-sm2 col-form-label fw-bolder"></label>
                <input asp-for="Complemento" class="form-control" id="Complemento" type="text" />
                 <input type="submit" class="btn btn-outline-info btn-lg" name="name" value="Cadastrar" />
            </div>
        </div>
    </form>
</div>

Views/Cliente/DetalhesCliente.cshtml
@model AulaDeASPNet.Models.Cliente

@{
    ViewData["Title"] = "DetalhesCliente";
    Layout = "~/Views/Shared/_NossoLayout.cshtml";
}

<h1>DetalhesCliente</h1>

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RG)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RG)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CPF)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CPF)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Usuario)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Usuario)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Senha)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Senha)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UF)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UF)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cidade)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cidade)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Bairro)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Bairro)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rua)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rua)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Numero)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Numero)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Complemento)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Complemento)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CEP)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CEP)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Telefone)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-warning" asp-action="AlterarCliente" asp-route-id="@Model?.Id">Alterar</a> |
    <a class="btn btn-primary" asp-action="BuscarCliente">Voltar para a lista</a>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/NossoApp/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
<div class="text-center">
    <h1>Primeira Pagina ASPPPPPPPPP</h1>
    <br />
    <h3>Opannn....</h3>
</div>

Views/Produto/AlterarProduto.cshtml
@model AulaDeASPNet.Models.Produto

@{
    ViewData["Title"] = "AlterarProduto";
    Layout = "~/Views/Shared/_NossoLayout.cshtml";
}

<h1>AlterarProduto</h1>

<h4>Produto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AlterarProduto">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Categoria" class="control-label"></label>
                <input asp-for="Categoria" class="form-control" />
                <span asp-validation-for="Categoria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Qtde" class="control-label"></label>
                <input asp-for="Qtde" class="form-control" />
                <span asp-validation-for="Qtde" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Peso" class="control-label"></label>
                <input asp-for="Peso" class="form-control" />
                <span asp-validation-for="Peso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Largura" class="control-label"></label>
                <input asp-for="Largura" class="form-control" />
                <span asp-validation-for="Largura" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Altura" class="control-label"></label>
                <input asp-for="Altura" class="form-control" />
                <span asp-validation-for="Altura" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-primary" asp-action="BuscarProduto">Voltar para a lista</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Shared/_NossoLayout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PrimeiroAspNet</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="~/assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <!-- links asp -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AulaDeASPNet.styles.css" asp-append-version="true" />
</head>
<body id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" asp-controller="NossoApp" asp-action="Index">Nosso App</a>
            <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Acesse Aqui
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" asp-controller="Cliente" asp-action="BuscarCliente">BClientes</a></li>
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" asp-controller="Cliente" asp-action="DetalhesCliente">DClientes</a></li>
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" asp-controller="Cliente" asp-action="CadastroCliente">CClientes</a></li>

                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" asp-controller="Produto" asp-action="BuscarProduto">Produtos</a></li>
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded">Contato</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <br />
    <br />
    <br />
    <br />
    <div class="container mt-4">
        <main role="main" class="m-2">
            @RenderBody()
        </main>
    </div>


    <!-- Footer-->
    <footer class="footer text-center">
        <div class="container">
            <div class="row">
                <!-- Footer Location-->
                <div class="col-lg-4 mb-5 mb-lg-0">
                    <h4 class="text-uppercase mb-4">Endereço</h4>
                    <p class="lead mb-0">
                        Vicente Magaglio, 50 - Anhangabaú
                        <br />
                        Jundiaí/SP CEP: 13200-359
                    </p>
                </div>
                <!-- Footer Social Icons-->
                <div class="col-lg-4 mb-5 mb-lg-0">
                    <h4 class="text-uppercase mb-4">Nossa Web</h4>
                    <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-facebook-f"></i></a>
                    <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-twitter"></i></a>
                    <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-linkedin-in"></i></a>
                    <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-dribbble"></i></a>
                </div>
                <!-- Footer About Text-->
                <div class="col-lg-4">
                    <h4 class="text-uppercase mb-4">Contatos</h4>
                    <p class="lead mb-0">
                        +551145871234 <br />
                        +551145871235 <br />
                        contatenos@outlook.com.br <br />
                        <a href="http://startbootstrap.com">Nossa Corporação</a>
                        .
                    </p>
                </div>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>